namespace JabraDesktop.App;

public static class UiTextCatalog
{
    static readonly IReadOnlyDictionary<UiText, string> German = new Dictionary<UiText, string>
    {
        [UiText.AppName] = "Jabra Desktop",
        [UiText.Open] = "Öffnen",
        [UiText.Autostart] = "Autostart",
        [UiText.Quit] = "Beenden",
        [UiText.Language] = "Sprache",
        [UiText.German] = "Deutsch",
        [UiText.English] = "English",
        [UiText.Appearance] = "Darstellung",
        [UiText.System] = "System",
        [UiText.Light] = "Hell",
        [UiText.Dark] = "Dunkel",
        [UiText.MoreActions] = "Weitere Aktionen",
        [UiText.MoreDeviceActions] = "Weitere Geräteaktionen",
        [UiText.UnpairMenu] = "Entkoppeln …",
        [UiText.BrandTagline] = "DEIN SOUND. DEINE VERBINDUNG.",
        [UiText.DevicesSection] = "DEINE GERÄTE",
        [UiText.DeviceRoleUnknown] = "Unbekannter Gerätetyp",
        [UiText.DeviceRoleHeadset] = "Headset",
        [UiText.DeviceRoleDongle] = "Bluetooth-Dongle",
        [UiText.DeviceRoleOther] = "Jabra-Gerät",
        [UiText.JabraUsb] = "Jabra USB",
        [UiText.LinuxDescription] = "Für Linux entwickelt.\nUnabhängige Desktop-App.",
        [UiText.Connections] = "VERBINDUNGEN",
        [UiText.SearchPairingSwitch] = "Suchen, koppeln und nahtlos wechseln.",
        [UiText.AddDevice] = "+ Gerät hinzufügen",
        [UiText.ConnectionProblem] = "Verbindung prüfen",
        [UiText.Reinitialize] = "Erneut initialisieren",
        [UiText.SavedDevices] = "Gespeicherte Geräte",
        [UiText.Refresh] = "Aktualisieren",
        [UiText.RefreshDeviceStatus] = "Gerätestatus aktualisieren",
        [UiText.RefreshingDeviceStatus] = "Status wird aktualisiert …",
        [UiText.NoPairs] = "Noch keine Kopplungen. Füge dein erstes Headset hinzu.",
        [UiText.NearbyDevices] = "Geräte in der Nähe",
        [UiText.StopSearch] = "Suche beenden",
        [UiText.PairingInstructions] = "Schalte dein Headset in den Pairing-Modus. Die Suche endet nach 30 Sekunden. Anschließend kannst du ein gefundenes Gerät koppeln.",
        [UiText.Battery] = "AKKU",
        [UiText.Firmware] = "FIRMWARE",
        [UiText.FeatureDependsOnDevice] = "Die verfügbaren Funktionen hängen vom angeschlossenen Gerät ab.",
        [UiText.DeviceTitleFallback] = "Deine Geräte, verbunden.",
        [UiText.PlugInDongle] = "Stecke deinen Jabra-Dongle ein, um loszulegen.",
        [UiText.BluetoothDongleSubtitle] = "Geräteverwaltung verfügbar",
        [UiText.UsbDeviceSubtitle] = "Jabra-Gerät · Über USB oder Dongle verbunden",
        [UiText.SearchingPairingMode] = "Suche nach Geräten im Pairing-Modus …",
        [UiText.DeviceActionRunning] = "Geräteaktion läuft …",
        [UiText.ReadyToConnect] = "Bereit zum Verbinden",
        [UiText.DeviceOverview] = "Geräteübersicht",
        [UiText.BatteryUnavailable] = "Nicht verfügbar",
        [UiText.FirmwareUnavailable] = "Nicht verfügbar",
        [UiText.SearchNoDevices] = "Keine Geräte gefunden. Prüfe den Pairing-Modus und starte die Suche erneut.",
        [UiText.SearchFoundOne] = "{0} Gerät gefunden. Wähle es zum Koppeln aus.",
        [UiText.SearchFoundMany] = "{0} Geräte gefunden. Wähle eines zum Koppeln aus.",
        [UiText.FoundForPairing] = "Zum Koppeln verfügbar",
        [UiText.Connected] = "Verbunden",
        [UiText.Disconnected] = "Nicht verbunden",
        [UiText.UnknownStatus] = "Status unbekannt",
        [UiText.Pair] = "Koppeln",
        [UiText.Disconnect] = "Trennen",
        [UiText.Connect] = "Verbinden",
        [UiText.ConsentTitle] = "Nutzungsbedingungen für Jabra-Komponenten",
        [UiText.ConsentSubtitle] = "Bitte lies die Bedingungen für die eingebundenen Jabra-Komponenten. Ohne Zustimmung startet die Geräteverwaltung nicht.",
        [UiText.AgreeAndContinue] = "Zustimmen und fortfahren",
        [UiText.DeclineAndExit] = "Ablehnen und beenden",
        [UiText.ConsentStorageFailure] = "Deine Zustimmung konnte nicht gespeichert werden. Jabra Desktop wird deshalb nicht gestartet.",
        [UiText.SettingsSaveFailure] = "Die Einstellung konnte nicht gespeichert werden.",
        [UiText.SettingsErrorTitle] = "Einstellung konnte nicht geändert werden",
        [UiText.AutostartFailureDetail] = "Der Autostart konnte nicht geändert werden.",
        [UiText.AutostartUnavailable] = "Der Autostart ist erst nach der Paketinstallation verfügbar.",
        [UiText.StartupErrorTitle] = "Jabra Desktop konnte nicht starten",
        [UiText.AutostartErrorTitle] = "Autostart konnte nicht geändert werden",
        [UiText.Close] = "Schließen",
        [UiText.UsbAccessDenied] = "USB-Zugriff verweigert. Installiere die Jabra-Zugriffsregel und stecke den Dongle neu ein.",
        [UiText.DeviceTimeout] = "Das Gerät antwortet nicht rechtzeitig. Aktualisiere den Verbindungsstatus und versuche es erneut.",
        [UiText.MissingSystemLibrary] = "Eine benötigte Systembibliothek fehlt. Prüfe die Einrichtung in der README.",
        [UiText.SelectSupportedDongle] = "Bitte wähle einen Bluetooth-Dongle mit unterstützter Geräteverwaltung aus.",
        [UiText.PeerNoLongerAvailable] = "Das Gerät ist nicht mehr verfügbar. Aktualisiere die Liste oder starte die Suche erneut.",
        [UiText.UnpairWindowTitle] = "Gerät entkoppeln",
        [UiText.Cancel] = "Abbrechen",
        [UiText.Unpair] = "Entkoppeln",
        [UiText.UnpairQuestion] = "„{0}“ wirklich entkoppeln?",
        [UiText.UnpairDescription] = "Die gespeicherte Kopplung wird vom Dongle entfernt. Zum erneuten Verbinden ist Pairing nötig.",
        [UiText.DongleRefreshError] = "Die Geräteliste dieses Dongles konnte nicht aktualisiert werden.",
        [UiText.StandaloneDevices] = "Weitere Geräte",
        [UiText.ViaDongle] = "Über {0}",
        [UiText.RenameBluetooth] = "Gerätenamen ändern…",
        [UiText.RenameBluetoothWindowTitle] = "Gerätenamen ändern",
        [UiText.RenameBluetoothDescription] = "Der Gerätename wird auf dem verbundenen Gerät gespeichert. Bei der Suche kann der neue Name erst nach einer erneuten Verbindung erscheinen.",
        [UiText.BluetoothNameLabel] = "Gerätename",
        [UiText.Save] = "Speichern"
    };

    static readonly IReadOnlyDictionary<UiText, string> English = new Dictionary<UiText, string>
    {
        [UiText.AppName] = "Jabra Desktop",
        [UiText.Open] = "Open",
        [UiText.Autostart] = "Autostart",
        [UiText.Quit] = "Quit",
        [UiText.Language] = "Language",
        [UiText.German] = "German",
        [UiText.English] = "English",
        [UiText.Appearance] = "Appearance",
        [UiText.System] = "System",
        [UiText.Light] = "Light",
        [UiText.Dark] = "Dark",
        [UiText.MoreActions] = "More actions",
        [UiText.MoreDeviceActions] = "More device actions",
        [UiText.UnpairMenu] = "Unpair…",
        [UiText.BrandTagline] = "YOUR SOUND. YOUR CONNECTION.",
        [UiText.DevicesSection] = "YOUR DEVICES",
        [UiText.DeviceRoleUnknown] = "Unknown device type",
        [UiText.DeviceRoleHeadset] = "Headset",
        [UiText.DeviceRoleDongle] = "Bluetooth dongle",
        [UiText.DeviceRoleOther] = "Jabra device",
        [UiText.JabraUsb] = "Jabra USB",
        [UiText.LinuxDescription] = "Made for Linux.\nIndependent desktop app.",
        [UiText.Connections] = "CONNECTIONS",
        [UiText.SearchPairingSwitch] = "Find, pair, and switch seamlessly.",
        [UiText.AddDevice] = "+ Add device",
        [UiText.ConnectionProblem] = "Check connection",
        [UiText.Reinitialize] = "Initialize again",
        [UiText.SavedDevices] = "Saved devices",
        [UiText.Refresh] = "Refresh",
        [UiText.RefreshDeviceStatus] = "Refresh device status",
        [UiText.RefreshingDeviceStatus] = "Refreshing status …",
        [UiText.NoPairs] = "No paired devices yet. Add your first headset.",
        [UiText.NearbyDevices] = "Nearby devices",
        [UiText.StopSearch] = "Stop search",
        [UiText.PairingInstructions] = "Put your headset in pairing mode. The search ends after 30 seconds. Then you can pair a device that was found.",
        [UiText.Battery] = "BATTERY",
        [UiText.Firmware] = "FIRMWARE",
        [UiText.FeatureDependsOnDevice] = "Available features depend on the connected device.",
        [UiText.DeviceTitleFallback] = "Your connected devices.",
        [UiText.PlugInDongle] = "Plug in your Jabra dongle to get started.",
        [UiText.BluetoothDongleSubtitle] = "Device management available",
        [UiText.UsbDeviceSubtitle] = "Jabra device · connected through USB or a dongle",
        [UiText.SearchingPairingMode] = "Searching for devices in pairing mode…",
        [UiText.DeviceActionRunning] = "Device action in progress…",
        [UiText.ReadyToConnect] = "Ready to connect",
        [UiText.DeviceOverview] = "Device overview",
        [UiText.BatteryUnavailable] = "Unavailable",
        [UiText.FirmwareUnavailable] = "Unavailable",
        [UiText.SearchNoDevices] = "No devices found. Check pairing mode and start the search again.",
        [UiText.SearchFoundOne] = "Found {0} device. Select it to pair.",
        [UiText.SearchFoundMany] = "Found {0} devices. Select one to pair.",
        [UiText.FoundForPairing] = "Available to pair",
        [UiText.Connected] = "Connected",
        [UiText.Disconnected] = "Disconnected",
        [UiText.UnknownStatus] = "Status unknown",
        [UiText.Pair] = "Pair",
        [UiText.Disconnect] = "Disconnect",
        [UiText.Connect] = "Connect",
        [UiText.ConsentTitle] = "Terms for Jabra components",
        [UiText.ConsentSubtitle] = "Review the terms for the included Jabra components. Device management will not start without your consent.",
        [UiText.AgreeAndContinue] = "Agree and continue",
        [UiText.DeclineAndExit] = "Decline and exit",
        [UiText.ConsentStorageFailure] = "Your consent could not be saved. Jabra Desktop will not start.",
        [UiText.SettingsSaveFailure] = "The setting could not be saved.",
        [UiText.SettingsErrorTitle] = "Could not change setting",
        [UiText.AutostartFailureDetail] = "Could not change the autostart setting.",
        [UiText.AutostartUnavailable] = "Autostart is available after installing the package.",
        [UiText.StartupErrorTitle] = "Jabra Desktop could not start",
        [UiText.AutostartErrorTitle] = "Could not change autostart",
        [UiText.Close] = "Close",
        [UiText.UsbAccessDenied] = "USB access denied. Install the Jabra access rule and reconnect the dongle.",
        [UiText.DeviceTimeout] = "The device did not respond in time. Refresh the connection status and try again.",
        [UiText.MissingSystemLibrary] = "A required system library is missing. Check the setup instructions in the README.",
        [UiText.SelectSupportedDongle] = "Select a Bluetooth dongle with supported device management.",
        [UiText.PeerNoLongerAvailable] = "The device is no longer available. Refresh the list or search again.",
        [UiText.UnpairWindowTitle] = "Unpair device",
        [UiText.Cancel] = "Cancel",
        [UiText.Unpair] = "Unpair",
        [UiText.UnpairQuestion] = "Unpair “{0}”?",
        [UiText.UnpairDescription] = "The saved pairing will be removed from the dongle. Pair the headset again before reconnecting.",
        [UiText.DongleRefreshError] = "This dongle's device list could not be refreshed.",
        [UiText.StandaloneDevices] = "Other devices",
        [UiText.ViaDongle] = "Via {0}",
        [UiText.RenameBluetooth] = "Change device name…",
        [UiText.RenameBluetoothWindowTitle] = "Change device name",
        [UiText.RenameBluetoothDescription] = "The device name is saved on the connected device. It may appear in searches after reconnecting.",
        [UiText.BluetoothNameLabel] = "Device name",
        [UiText.Save] = "Save"
    };

    public static string Get(UiLanguage language, UiText key)
    {
        var catalog = language switch
        {
            UiLanguage.German => German,
            UiLanguage.English => English,
            _ => throw new ArgumentOutOfRangeException(nameof(language), language, "Unsupported UI language.")
        };

        return catalog.TryGetValue(key, out var value)
            ? value
            : throw new ArgumentOutOfRangeException(nameof(key), key, "No translation is defined for this UI text.");
    }
}
