<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../JabraDesktop.Core/JabraDesktop.Core.csproj" /><PackageReference Include="Jabra.NET.Sdk" Version="4.9.1.1" /><PackageReference Include="Jabra.NET.Sdk.DevicePairing" Version="3.1.1.2" /><PackageReference Include="Jabra.NET.Sdk.Properties" Version="2.5.1.1" /></ItemGroup></Project>
